name: Release CLI

on:
  push:
    branches:
      - main
    paths:
      # a) API spec changes
      - "fern/openapi.yml"
      - "fern/openapi-overlay.yml"
      # b) Fern CLI version changes
      - "fern/fern.config.json"
      # c) Generator version changes
      - "fern/generators.yml"
  pull_request:
    paths:
      - "fern/openapi.yml"
      - "fern/openapi-overlay.yml"
      - "fern/fern.config.json"
      - "fern/generators.yml"
  workflow_dispatch:

jobs:
  preview-and-validate:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-A warnings"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Fern CLI
        uses: fern-api/setup-fern-cli@v1

      - name: Generate preview
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --group cli --preview --output ./preview --log-level debug

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Check
        working-directory: ./preview/fern-cli-generator
        run: cargo check

      - name: Build
        working-directory: ./preview/fern-cli-generator
        run: cargo build

      - name: Test
        working-directory: ./preview/fern-cli-generator
        run: cargo test

  release:
    needs: preview-and-validate
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Fern CLI
        uses: fern-api/setup-fern-cli@v1

      - name: Generate CLI
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --group cli --log-level debug --version AUTO
