name: Fern Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Fern CLI
        uses: fern-api/setup-fern-cli@v1

      - name: Fern check
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern check
